version: '3.8'

networks:
  services:
    name: user

services:
  galactic-price-advice:
    container_name: galactic-price-advice
    build:
      context: ./price-advice-mock
    networks:
      - services
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/__admin/requests || exit 1" ]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 3
    ports:
      - "8089:8080"