version: '3.8'

services:
  galactic-pet-emporium:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: galactic_pet_emporium
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  price-advice-mock:
    build:
      context: ./price-advice-mock
      dockerfile: Dockerfile
    ports:
      - "8081:8081"