spring:
  application:
    name: cosmo-cats-api
server:
  port: 9090

application:
  rest-client:
    response-timeout: 1000
  price-advisor-service:
    base-path: http://localhost:8089
    advisor: ${application.price-advisor-service.base-path}/api/v1/price-comparison

features:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false
  enabled:
    new-pricing-algorithm: true
    enhanced-search: false
    premium-features: false